### ISSUE TITLE
求课程地址

### ISSUE THREAD

**Issue by kamasylvia** [52ABP/52ABP.School#1]
百度传课我用了三款浏览器都播放不了,好像必须要flash. 网易云课堂里面没有内容. 
有没有其他途径?

**Comment by ltm0203** [comment]
目前还在协商其他途径。如果看不了可以退款，过几天会上架到腾讯课堂

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ltm0203** [comment]
目前已经在腾讯课堂和网易云课堂上架了。你可以加群联系我。633751348 我们协商解决这个事情。
